### ISSUE TITLE
Use a game engine instead of tkinter?

### ISSUE THREAD

**Issue by Guppster** [paul-bartlett/Snake#1]
We may want to use something like [pygame](http://www.pygame.org/) to simplify the process. 
I dont think tkinter is appropriate for animations/making a game?

Let me know what you think

**Comment by paul-bartlett** [comment]
I was thinking about using that as well. It didn't seem that complex to do with either one so if you want to switch over that's fine.

**Comment by Guppster** [comment]
Sounds good, i'll look into it tonight. I'm pretty sure pygame should be easier. We can rebuild it with tkinter once we're better at python for a challenge

**Comment by paul-bartlett** [comment]
Meet me at lumbridge tonight and we'll figure it out

**Comment by Guppster** [comment]
Bring the brass key, we'll gather big bones after :)
